// <auto-generated />
using System;
using BookingService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookingService.Infrastructure.Data.Migrations;

[DbContext(typeof(BookingDbContext))]
partial class BookingDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("BookingService.Entities.Booking", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("bigint")
                .HasColumnName("id");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

            b.Property<DateOnly>("BookedFrom")
                .HasColumnType("date")
                .HasColumnName("booked_from");

            b.Property<DateOnly>("BookedTo")
                .HasColumnType("date")
                .HasColumnName("booked_to");

            b.Property<Guid?>("CatalogRequestId")
                .HasColumnType("uuid")
                .HasColumnName("catalog_request_id");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<long>("ResourceId")
                .HasColumnType("bigint")
                .HasColumnName("resource_id");

            b.Property<int>("Status")
                .HasColumnType("integer")
                .HasColumnName("status");

            b.Property<long>("UserId")
                .HasColumnType("bigint")
                .HasColumnName("user_id");

            b.HasKey("Id");

            b.HasIndex("ResourceId")
                .HasDatabaseName("idx_bookings_resource_id");

            b.HasIndex("Status")
                .HasDatabaseName("idx_bookings_status");

            b.HasIndex("UserId")
                .HasDatabaseName("idx_bookings_user_id");

            b.ToTable("bookings");
        });
#pragma warning restore 612, 618
    }
}
